version: '3.8'

services:
  dbt:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: dbank_dbt_init
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - APP_USER=${APP_USER}
      - APP_PASSWORD=${APP_PASSWORD}
      - DBT_USER=${DBT_USER}
      - DBT_PASSWORD=${DBT_PASSWORD}
    networks:
      - backend-network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
    command: >
      bash -c "pip install dbt-postgres && python scripts/generate_mock_data.py && cd data/dbank_analytics && dbt deps && dbt run"
    restart: "no"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: dbank_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - APP_USER=${APP_USER}
      - APP_PASSWORD=${APP_PASSWORD}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - frontend-network
      - backend-network
    depends_on:
      db:
        condition: service_healthy
      dbt:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    container_name: dbank_frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - frontend-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: pgvector/pgvector:pg15
    container_name: dbank_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
      DBT_USER: ${DBT_USER}
      DBT_PASSWORD: ${DBT_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - backend-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  postgres_data:
